### ISSUE TITLE
Crash on Hours tab of dining

### ISSUE THREAD

**Issue by adelq** [pennlabs/penn-mobile-android#452] opened 2017-12-15 13:35 UTC
Highly reproducible.

1. Open dining
2. Open a dining hall
3. Open Hours tab
4. Let your phone go to sleep due to inactivity (or push power button to make it go to sleep)
5. Crash!

**Comment by andrewsi10** [comment] 2017-12-15 23:04
We've actually already determined the source of the bug and fixed it - we haven't pushed the fix to GitHub yet. The cause is when the method [setPagerPosition()](https://github.com/pennlabs/penn-mobile-android/blob/master/PennMobile/src/main/java/com/pennapps/labs/pennmobile/MenuFragment.java#L131) in MenuFragment is called. Deleting the method fixes the problem and we haven't noticed any change in functionality by removing the method.

**Comment by andrewsi10** [comment] 2018-03-12 02:29
[Fixed!](https://github.com/pennlabs/penn-mobile-android/pull/463)

**Closed by andrewsi10** 2018-03-12 02:29 UTC
Labels: bug
